name: Production

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run sbt clean compile
        run: |
          sbt clean compile
  deploy:
    name: deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run sbt stage deployHeroku
        env:
          ZEEBE_BROKER: ${{secrets.ZEEBE_BROKER}}
          ZEEBE_CLIENT_ID: ${{secrets.ZEEBE_CLIENT_ID}}
          ZEEBE_CLIENT_SECRET: ${{secrets.ZEEBE_CLIENT_SECRET}}
          HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY }}
          LOG_LEVEL: DEBUG
          HOST: 0.0.0.0
          SWAGGER_SCHEMES: https
          SWAGGER_HOST: prod-kezek-zeebe-worker.herokuapp.com
          ENV: prod
        run: |
          sbt -Denv=prod stage deployHeroku
